/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jabrena' at '7/02/17 21:20' with Gradle 2.4
 *
 * @author jabrena, @date 7/02/17 21:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
